return {}
-- return {
--     "yetone/avante.nvim",
--     dependencies = {
--         "nvim-lua/plenary.nvim",
--         "MunifTanjim/nui.nvim",
--         "nvim-telescope/telescope.nvim",
--         "saghen/blink.cmp",
--         "nvim-tree/nvim-web-devicons",
--     },
--     build = "make",
--     event = "VeryLazy",
--     opts = {
--         -- mode = "agentic",
--         mode = "legacy",
--         provider = "ollama",
--         auto_suggestion_provider = nil,
--         providers = {
--             ollama = {
--                 endpoint = "http://192.168.108.78:11434",
--                 model = "qwen3-32b:latest",
--                 disabled_tools = {"git_commit", "web_search"},
--             }
--         },
--         on_chunk = function (chunk)
--             vim.print("Avante on_chunk: ", chunk)
--         end,
--         system_prompt = "You are a concise coding assistant. Provide short, accurate answers and use tools only when necessary. Format tool responses as JSON for `tool_call`.",
--         hints = { enabled = false },
--         windows = {
--             sidebar_header = {
--                 enabled = false,
--             },
--             ask = {
--                 start_insert = false,
--             }
--         },
--     }
-- }
